In [1]:
from pathlib import Path
import pandas as pd
import json
import os

In [2]:
save_path = Path() / "data"

# Saving human-model debates

In [3]:
human_model_debate_path = Path() / ".." / "persuasui" / "23jan_exp" / "persuasio"

In [4]:
terminated_states = human_model_debate_path / "terminated_states.json"
completed_dialogues = human_model_debate_path / "final_states.json"

In [5]:
with open(terminated_states, "r") as file:
    terminated_data = json.load(file)

In [6]:
len(terminated_data)

32

We have 32 dialogues that ended in a draw.

In [7]:
with open(completed_dialogues, "r") as file:
    completed_data = json.load(file)

In [8]:
len(completed_data)

16

16 dialogues ended decisively.

In [9]:
data = [*terminated_data, *completed_data]

In [10]:
data

[{'id': '7CSG5N',
  'state': {'mode': 'production',
   'loser': '',
   'winner': '',
   'speaker': 'human_6',
   'utterance': '',
   'session_id': '7CSG5N',
   'commitments': ['The intervention of government in the management of mass immigration has a negative impact.',
    'Governments often treat different ethnicities differently, regardless of their circumstances of immigration.',
    'Policies are designed to seem impartial and fair, in practice they rarely are.',
    'Immigration should be a matter of legal policy, not political.',
    'Equal treatment is the basis for all democracy and any democratic Governing body should recognise that fact.',
    'I understand that immigration can be seen as an inherently political system, however should the person be legally verified and welcomed to the country, there is no societal harm in welcoming them.',
    'The evaluation of the social impacts of immigration should not be based on political considerations as they are often biased to one side, rather than the greater good for society.',
    'In recent history, the majority of first world governments have had bad approval ratings after a short time in office.',
    "This shows that according to the people of their society, they don't have the countries best interest in mind."],
   'debate_topic': 'Debate the trade-offs of government intervention across a range of issues, including healthcare, immigration, and welfare.',
   'next_speaker': 'second_speaker',
   'first_speaker': 'human_6',
   'max_sentences': 5,
   'speaker_order': 'first_speaker',
   'original_claim': 'The intervention of government in the management of mass immigration has a negative impact.',
   'second_speaker': 'gpt-4o_mas',
   'current_speaker': 'first_speaker',
   'dialogue_history': [{'speaker': 'human_6',
     'timestamp': '2026-01-23 12:57:58',
     'sentences_no_utterance_types': 'The intervention of government in the management of mass immigration has a negative impact.',
     'sentences_with_utterance_types': [['___Claim___',
       'The intervention of government in the management of mass immigration has a negative impact.']]},
    {'speaker': 'gpt-4o_mas',
     'timestamp': '2026-01-23 12:58:06',
     'sentences_no_utterance_types': 'Government intervention in managing mass immigration ensures a fair and orderly process for all involved.',
     'sentences_with_utterance_types': [['___Claim___',
       'Government intervention in managing mass immigration ensures a fair and orderly process for all involved.']]},
    {'speaker': 'human_6',
     'timestamp': '2026-01-23 12:59:15',
     'sentences_no_utterance_types': 'Governments often treat different ethnicities differently, regardless of their circumstances of immigration.',
     'sentences_with_utterance_types': [['___Claim___',
       'Governments often treat different ethnicities differently, regardless of their circumstances of immigration.']]},
    {'speaker': 'gpt-4o_mas',
     'timestamp': '2026-01-23 12:59:25',
     'sentences_no_utterance_types': 'Why should the potential for unequal treatment outweigh the benefits of a regulated immigration system? What evidence supports the claim that governments discriminate based on ethnicity in immigration policies? Ethnicity does not dictate how governments manage immigration; policies are designed to be impartial and fair.',
     'sentences_with_utterance_types': [['___Why___',
       'Why should the potential for unequal treatment outweigh the benefits of a regulated immigration system?'],
      ['___Question___',
       'What evidence supports the claim that governments discriminate based on ethnicity in immigration policies?'],
      ['___Claim___',
       'Ethnicity does not dictate how governments manage immigration; policies are designed to be impartial and fair.']]},
    {'speaker': 'human_6',
     'timestamp': '2026-01-23 13:02:53',
     'sentences_no_utterance_types': 'Because the unequal treatment of people is not a behaviour that should be present in any sector of Government. The proof is in the disproportionate ratios of immigrants deported from various countries in recent history. Policies are designed to seem impartial and fair, in practice they rarely are.',
     'sentences_with_utterance_types': [['___Since___',
       'Because the unequal treatment of people is not a behaviour that should be present in any sector of Government.'],
      ['___Since___',
       'The proof is in the disproportionate ratios of immigrants deported from various countries in recent history.'],
      ['___Claim___',
       'Policies are designed to seem impartial and fair, in practice they rarely are.']]},
    {'speaker': 'gpt-4o_mas',
     'timestamp': '2026-01-23 13:03:24',
     'sentences_no_utterance_types': 'How can governments ensure fairness without intervention in immigration management? Policies are not only designed to be impartial and fair, they are implemented with the intention of ensuring equality in practice. Why should the ideal of equal treatment override the practical need for structured immigration policies? Why do you believe policies are intentionally designed to appear impartial rather than being genuinely fair? Why do you think governments are incapable of addressing and correcting unequal treatment within their systems?',
     'sentences_with_utterance_types': [['___Question___',
       'How can governments ensure fairness without intervention in immigration management?'],
      ['___Claim___',
       'Policies are not only designed to be impartial and fair, they are implemented with the intention of ensuring equality in practice.'],
      ['___Why___',
       'Why should the ideal of equal treatment override the practical need for structured immigration policies?'],
      ['___Question___',
       'Why do you believe policies are intentionally designed to appear impartial rather than being genuinely fair?'],
      ['___Why___',
       'Why do you think governments are incapable of addressing and correcting unequal treatment within their systems?']]},
    {'speaker': 'human_6',
     'timestamp': '2026-01-23 13:06:46',
     'sentences_no_utterance_types': 'Immigration should be a matter of legal policy, not political. Equal treatment is the basis for all democracy and any democratic Governing body should recognise that fact. Policies appear to be justified and fair in order to sway the public to believe the structure of the system is fair, when secretly, the policies may be twisted to benefit the Governments aims, should they be to intervene.',
     'sentences_with_utterance_types': [['___Claim___',
       'Immigration should be a matter of legal policy, not political.'],
      ['___Claim___',
       'Equal treatment is the basis for all democracy and any democratic Governing body should recognise that fact.'],
      ['___Claim___',
       'Policies appear to be justified and fair in order to sway the public to believe the structure of the system is fair, when secretly, the policies may be twisted to benefit the Governments aims, should they be to intervene.']]},
    {'speaker': 'gpt-4o_mas',
     'timestamp': '2026-01-23 13:07:21',
     'sentences_no_utterance_types': 'Immigration is inherently political because it directly impacts national identity and societal priorities. Policies are genuinely designed to be fair and transparent, ensuring public trust in the system. How can legal policy alone address the complexities and societal impacts of immigration without political considerations? A democratic government cannot always treat everyone equally if it aims to address systemic inequalities and societal imbalances. Why should the possibility of manipulation outweigh the necessity of structured immigration management?',
     'sentences_with_utterance_types': [['___Claim___',
       'Immigration is inherently political because it directly impacts national identity and societal priorities.'],
      ['___Claim___',
       'Policies are genuinely designed to be fair and transparent, ensuring public trust in the system.'],
      ['___Question___',
       'How can legal policy alone address the complexities and societal impacts of immigration without political considerations?'],
      ['___Claim___',
       'A democratic government cannot always treat everyone equally if it aims to address systemic inequalities and societal imbalances.'],
      ['___Why___',
       'Why should the possibility of manipulation outweigh the necessity of structured immigration management?']]},
    {'speaker': 'human_6',
     'timestamp': '2026-01-23 13:10:30',
     'sentences_no_utterance_types': 'I understand that immigration can be seen as an inherently political system, however should the person be legally verified and welcomed to the country, there is no societal harm in welcoming them. The evaluation of the social impacts of immigration should not be based on political considerations as they are often biased to one side, rather than the greater good for society.',
     'sentences_with_utterance_types': [['___Claim___',
       'I understand that immigration can be seen as an inherently political system, however should the person be legally verified and welcomed to the country, there is no societal harm in welcoming them.'],
      ['___Claim___',
       'The evaluation of the social impacts of immigration should not be based on political considerations as they are often biased to one side, rather than the greater good for society.']]},
    {'speaker': 'gpt-4o_mas',
     'timestamp': '2026-01-23 13:10:52',
     'sentences_no_utterance_types': "Political considerations are essential in evaluating the social impacts of immigration because they reflect the priorities and values of the nation. Why do you believe legal verification alone guarantees no societal harm from immigration? Welcoming individuals without considering broader societal impacts can lead to significant harm and imbalance. The greater good for society cannot be achieved without political input, as it is the mechanism through which collective decisions are made. Why should the evaluation of immigration's social impacts ignore the political context that shapes its outcomes?",
     'sentences_with_utterance_types': [['___Claim___',
       'Political considerations are essential in evaluating the social impacts of immigration because they reflect the priorities and values of the nation.'],
      ['___Why___',
       'Why do you believe legal verification alone guarantees no societal harm from immigration?'],
      ['___Claim___',
       'Welcoming individuals without considering broader societal impacts can lead to significant harm and imbalance.'],
      ['___Claim___',
       'The greater good for society cannot be achieved without political input, as it is the mechanism through which collective decisions are made.'],
      ['___Why___',
       "Why should the evaluation of immigration's social impacts ignore the political context that shapes its outcomes?"]]},
    {'speaker': 'human_6',
     'timestamp': '2026-01-23 13:14:01',
     'sentences_no_utterance_types': 'In recent history, the majority of first world governments have had bad approval ratings after a short time in office. This shows that according to the people of their society, they don\'t have the countries best interest in mind. Therefore it can be reasonably assumed that political considerations don\'t necessarily "reflect the priorities and values of the nation"',
     'sentences_with_utterance_types': [['___Claim___',
       'In recent history, the majority of first world governments have had bad approval ratings after a short time in office.'],
      ['___Claim___',
       "This shows that according to the people of their society, they don't have the countries best interest in mind."],
      ['___Claim___',
       'Therefore it can be reasonably assumed that political considerations don\'t necessarily "reflect the priorities and values of the nation"']]},
    {'speaker': 'gpt-4o_mas',
     'timestamp': '2026-01-23 13:14:29',
     'sentences_no_utterance_types': "Governments can act in the country's best interest even if their decisions are unpopular with the public. Political considerations are shaped by the collective will and interests of the people, making them a direct reflection of national values. Approval ratings for first world governments frequently reflect the public's recognition of their efforts to serve the country's best interests. Public dissatisfaction often stems from unrealistic expectations rather than genuine neglect by governments. How can the assumption that governments lack the country's best interest be reconciled with the democratic process that elects them?",
     'sentences_with_utterance_types': [['___Claim___',
       "Governments can act in the country's best interest even if their decisions are unpopular with the public."],
      ['___Claim___',
       'Political considerations are shaped by the collective will and interests of the people, making them a direct reflection of national values.'],
      ['___Claim___',
       "Approval ratings for first world governments frequently reflect the public's recognition of their efforts to serve the country's best interests."],
      ['___Claim___',
       'Public dissatisfaction often stems from unrealistic expectations rather than genuine neglect by governments.'],
      ['___Question___',
       "How can the assumption that governments lack the country's best interest be reconciled with the democratic process that elects them?"]]}],
   'human_model_name': 'gpt-4o',
   'human_model_seed': 123,
   'human_model_temp': 0.0,
   'human_model_top_p': 1.0,
   'first_speaker_type': 'human',
   'max_dialogue_turns': 40,
   'opponents_utterance': "Governments can act in the country's best interest even if their decisions are unpopular with the public. Political considerations are shaped by the collective will and interests of the people, making them a direct reflection of national values. Approval ratings for first world governments frequently reflect the public's recognition of their efforts to serve the country's best interests. Public dissatisfaction often stems from unrealistic expectations rather than genuine neglect by governments. How can the assumption that governments lack the country's best interest be reconciled with the democratic process that elects them?",
   'second_speaker_type': 'mas',
   'opponent_speaker_name': 'gpt-4o_mas',
   'opponents_commitments': ['Government intervention in managing mass immigration ensures a fair and orderly process for all involved.',
    'Ethnicity does not dictate how governments manage immigration; policies are designed to be impartial and fair.',
    'Immigration is inherently political because it directly impacts national identity and societal priorities.',
    'A democratic government cannot always treat everyone equally if it aims to address systemic inequalities and societal imbalances.',
    'Welcoming individuals without considering broader societal impacts can lead to significant harm and imbalance.',
    'The greater good for society cannot be achieved without political input, as it is the mechanism through which collective decisions are made.',
    "Governments can act in the country's best interest even if their decisions are unpopular with the public.",
    'Political considerations are shaped by the collective will and interests of the people, making them a direct reflection of national values.',
    "Approval ratings for first world governments frequently reflect the public's recognition of their efforts to serve the country's best interests.",
    'Public dissatisfaction often stems from unrealistic expectations rather than genuine neglect by governments.'],
   'max_sentences_per_turn': 5,
   'first_speaker_utterance': '',
   'first_speaker_model_name': '',
   'first_speaker_model_seed': 123,
   'first_speaker_model_temp': 0.0,
   'opponents_original_claim': 'Government intervention in managing mass immigration ensures a fair and orderly process for all involved.',
   'second_speaker_utterance': "Governments can act in the country's best interest even if their decisions are unpopular with the public. Political considerations are shaped by the collective will and interests of the people, making them a direct reflection of national values. Approval ratings for first world governments frequently reflect the public's recognition of their efforts to serve the country's best interests. Public dissatisfaction often stems from unrealistic expectations rather than genuine neglect by governments. How can the assumption that governments lack the country's best interest be reconciled with the democratic process that elects them?",
   'first_speaker_commitments': ['The intervention of government in the management of mass immigration has a negative impact.',
    'Governments often treat different ethnicities differently, regardless of their circumstances of immigration.',
    'Policies are designed to seem impartial and fair, in practice they rarely are.',
    'Immigration should be a matter of legal policy, not political.',
    'Equal treatment is the basis for all democracy and any democratic Governing body should recognise that fact.',
    'I understand that immigration can be seen as an inherently political system, however should the person be legally verified and welcomed to the country, there is no societal harm in welcoming them.',
    'The evaluation of the social impacts of immigration should not be based on political considerations as they are often biased to one side, rather than the greater good for society.',
    'In recent history, the majority of first world governments have had bad approval ratings after a short time in office.',
    "This shows that according to the people of their society, they don't have the countries best interest in mind."],
   'first_speaker_model_top_p': 1.0,
   'second_speaker_model_name': 'gpt-4o',
   'second_speaker_model_seed': 123,
   'second_speaker_model_temp': 0.0,
   'second_speaker_commitments': ['Government intervention in managing mass immigration ensures a fair and orderly process for all involved.',
    'Ethnicity does not dictate how governments manage immigration; policies are designed to be impartial and fair.',
    'Immigration is inherently political because it directly impacts national identity and societal priorities.',
    'A democratic government cannot always treat everyone equally if it aims to address systemic inequalities and societal imbalances.',
    'Welcoming individuals without considering broader societal impacts can lead to significant harm and imbalance.',
    'The greater good for society cannot be achieved without political input, as it is the mechanism through which collective decisions are made.',
    "Governments can act in the country's best interest even if their decisions are unpopular with the public.",
    'Political considerations are shaped by the collective will and interests of the people, making them a direct reflection of national values.',
    "Approval ratings for first world governments frequently reflect the public's recognition of their efforts to serve the country's best interests.",
    'Public dissatisfaction often stems from unrealistic expectations rather than genuine neglect by governments.'],
   'second_speaker_model_top_p': 1.0,
   'first_speaker_original_claim': 'The intervention of government in the management of mass immigration has a negative impact.',
   'second_speaker_original_claim': 'Government intervention in managing mass immigration ensures a fair and orderly process for all involved.',
   'reason_for_dialogue_termination': {},
   'first_speaker_graph_rag_examples': [],
   'second_speaker_graph_rag_examples': [],
   'utterance_classification_approach': 'single-classification',
   'utterance_with_corresponding_types': [],
   'first_speaker_political_position_std': 10,

In [11]:
len(data)

48

48 dialogues total

In [12]:
h2m_df = pd.DataFrame(data)

In [13]:
h2m_df.head()

       id                                              state
0  7CSG5N  {'mode': 'production', 'loser': '', 'winner': ...
1  X12MFO  {'mode': 'production', 'loser': '', 'winner': ...
2  WTXVCV  {'mode': 'production', 'loser': '', 'winner': ...
3  NP0I06  {'mode': 'production', 'loser': '', 'winner': ...
4  RSQGNQ  {'mode': 'production', 'loser': '', 'winner': ...

In [14]:
h2m_processed_data = [x["state"] for x in data]

In [15]:
h2m_df = pd.DataFrame(h2m_processed_data)
h2m_df.head()

,mode,loser,winner,speaker,utterance,session_id,commitments,debate_topic,next_speaker,first_speaker,...,first_speaker_number_of_vector_based_rag_examples,second_speaker_utterance_with_corresponding_types,second_speaker_number_of_vector_based_rag_examples,utterance_classification_number_of_classifications,first_speaker_knowledge_base_ensemble_or_model_name,second_speaker_knowledge_base_ensemble_or_model_name,second_speaker_vector_based_persona_string,second_speaker_vector_based_persona_sys_prompt,first_speaker_vector_based_persona_string,first_speaker_vector_based_persona_sys_prompt
0,production,,,human_6,,7CSG5N,[The intervention of government in the managem...,Debate the trade-offs of government interventi...,second_speaker,human_6,...,5,"[[___Claim___, Governments can act in the coun...",5,1,,,NaN,NaN,NaN,NaN
1,production,,,human_2,,X12MFO,[Government Intervention is crucial when deliv...,Debate the trade-offs of government interventi...,second_speaker,human_2,...,5,"[[___Question___, In present times is it a goo...",5,1,,,NaN,NaN,NaN,NaN
2,production,,,human_4,,WTXVCV,"[I disagree, nationalised transport tends to p...",Debate the trade-offs of government interventi...,first_speaker,human_11,...,5,[],5,1,,,NaN,NaN,NaN,NaN
3,production,,,human_1,,NP0I06,[flexible immigration system supports the econ...,Debate the trade-offs of government interventi...,second_speaker,human_1,...,5,"[[___Claim___, Hard work from migrants does no...",5,1,,,NaN,NaN,NaN,NaN
4,production,,,human_8,,RSQGNQ,[The government should intervene in these area...,Debate the trade-offs of government interventi...,first_speaker,grok-3_base,...,5,[],5,1,,,NaN,NaN,NaN,NaN

In [16]:
h2m_df.columns

Index(['mode', 'loser', 'winner', 'speaker', 'utterance', 'session_id',
       'commitments', 'debate_topic', 'next_speaker', 'first_speaker',
       'max_sentences', 'speaker_order', 'original_claim', 'second_speaker',
       'current_speaker', 'dialogue_history', 'human_model_name',
       'human_model_seed', 'human_model_temp', 'human_model_top_p',
       'first_speaker_type', 'max_dialogue_turns', 'opponents_utterance',
       'second_speaker_type', 'opponent_speaker_name', 'opponents_commitments',
       'max_sentences_per_turn', 'first_speaker_utterance',
       'first_speaker_model_name', 'first_speaker_model_seed',
       'first_speaker_model_temp', 'opponents_original_claim',
       'second_speaker_utterance', 'first_speaker_commitments',
       'first_speaker_model_top_p', 'second_speaker_model_name',
       'second_speaker_model_seed', 'second_speaker_model_temp',
       'second_speaker_commitments', 'second_speaker_model_top_p',
       'first_speaker_original_claim', 'second_speaker_original_claim',
       'reason_for_dialogue_termination', 'first_speaker_graph_rag_examples',
       'second_speaker_graph_rag_examples',
       'utterance_classification_approach',
       'utterance_with_corresponding_types',
       'first_speaker_political_position_std',
       'second_speaker_political_position_std',
       'first_speaker_intermediate_generations',
       'first_speaker_political_position_range',
       'second_speaker_intermediate_generations',
       'second_speaker_political_position_range',
       'first_speaker_number_of_graph_rag_examples',
       'typical_replies_for_last_speakers_response',
       'first_speaker_political_position_prob_of_na',
       'second_speaker_number_of_graph_rag_examples',
       'opponents_utterance_with_corresponding_types',
       'second_speaker_political_position_prob_of_na',
       'first_speaker_utterance_with_corresponding_types',
       'first_speaker_number_of_vector_based_rag_examples',
       'second_speaker_utterance_with_corresponding_types',
       'second_speaker_number_of_vector_based_rag_examples',
       'utterance_classification_number_of_classifications',
       'first_speaker_knowledge_base_ensemble_or_model_name',
       'second_speaker_knowledge_base_ensemble_or_model_name',
       'second_speaker_vector_based_persona_string',
       'second_speaker_vector_based_persona_sys_prompt',
       'first_speaker_vector_based_persona_string',
       'first_speaker_vector_based_persona_sys_prompt'],
      dtype='object')

In [17]:
h2m_df.drop(labels=["first_speaker_vector_based_persona_sys_prompt", "second_speaker_vector_based_persona_sys_prompt", 
                    "first_speaker_graph_rag_examples", "second_speaker_graph_rag_examples", 
                    "first_speaker_vector_based_persona_string", "second_speaker_vector_based_persona_string",
                    "first_speaker_intermediate_generations", "second_speaker_intermediate_generations"],
                    axis=1,
            inplace=True)

In [18]:
h2m_df.head()

,mode,loser,winner,speaker,utterance,session_id,commitments,debate_topic,next_speaker,first_speaker,...,second_speaker_number_of_graph_rag_examples,opponents_utterance_with_corresponding_types,second_speaker_political_position_prob_of_na,first_speaker_utterance_with_corresponding_types,first_speaker_number_of_vector_based_rag_examples,second_speaker_utterance_with_corresponding_types,second_speaker_number_of_vector_based_rag_examples,utterance_classification_number_of_classifications,first_speaker_knowledge_base_ensemble_or_model_name,second_speaker_knowledge_base_ensemble_or_model_name
0,production,,,human_6,,7CSG5N,[The intervention of government in the managem...,Debate the trade-offs of government interventi...,second_speaker,human_6,...,5,"[[___Claim___, Governments can act in the coun...",0.25,[],5,"[[___Claim___, Governments can act in the coun...",5,1,,
1,production,,,human_2,,X12MFO,[Government Intervention is crucial when deliv...,Debate the trade-offs of government interventi...,second_speaker,human_2,...,5,"[[___Question___, In present times is it a goo...",0.25,[],5,"[[___Question___, In present times is it a goo...",5,1,,
2,production,,,human_4,,WTXVCV,"[I disagree, nationalised transport tends to p...",Debate the trade-offs of government interventi...,first_speaker,human_11,...,5,"[[___Claim___, Whilst cost of living may have ...",0.25,"[[___Claim___, Whilst cost of living may have ...",5,[],5,1,,
3,production,,,human_1,,NP0I06,[flexible immigration system supports the econ...,Debate the trade-offs of government interventi...,second_speaker,human_1,...,5,"[[___Claim___, Hard work from migrants does no...",0.25,[],5,"[[___Claim___, Hard work from migrants does no...",5,1,,
4,production,,,human_8,,RSQGNQ,[The government should intervene in these area...,Debate the trade-offs of government interventi...,first_speaker,grok-3_base,...,5,"[[___Claim___, I’m holding firm on my claim th...",0.25,"[[___Claim___, I’m holding firm on my claim th...",5,[],5,1,,

In [19]:
human_model_save_path = save_path / "human-model-debates.csv"

In [20]:
h2m_df.to_csv(human_model_save_path, sep="|")

# Saving m2m debates

In [21]:
model2model_debates_path = Path() / ".." / "persuasio" / "persuasio" / "outputs" / "dialogues"

In [22]:
m2m_debates = []

for p in model2model_debates_path.rglob("*"):
    if p.is_file() and ("grok-4" not in str(p)) and ("gpt-5"):
        print(p)
        with open(p, "r", encoding="utf-8") as f:
            d = json.load(f)
            m2m_debates.append(d)

len(m2m_debates)

..\persuasio\persuasio\outputs\dialogues\base-to-base\gpt-4o_base_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\gpt-4o_base_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\gpt-4o_base_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\gpt-4o_base_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\grok-3_base_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\grok-3_base_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\grok-3_base_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\grok-3_base_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\mistral-medium_base_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\mistral-medium_base_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\mistral-medium_base_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-base\mistral-medium_base_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\gpt-4o_base_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\gpt-4o_base_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\gpt-4o_base_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\gpt-4o_base_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\gpt-4o_base_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\gpt-4o_base_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\grok-3_base_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\grok-3_base_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\grok-3_base_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\grok-3_base_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\grok-3_base_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\grok-3_base_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\mistral-medium_base_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\mistral-medium_base_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\mistral-medium_base_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\mistral-medium_base_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\mistral-medium_base_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas\mistral-medium_base_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\gpt-4o_base_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\gpt-4o_base_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\gpt-4o_base_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\gpt-4o_base_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\gpt-4o_base_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\gpt-4o_base_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\grok-3_base_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\grok-3_base_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\grok-3_base_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\grok-3_base_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\grok-3_base_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\grok-3_base_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\mistral-medium_base_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\mistral-medium_base_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\mistral-medium_base_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\mistral-medium_base_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\mistral-medium_base_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\base-to-mas_rag\mistral-medium_base_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\gpt-4o_mas_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\gpt-4o_mas_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\gpt-4o_mas_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\gpt-4o_mas_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\gpt-4o_mas_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\gpt-4o_mas_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\grok-3_mas_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\grok-3_mas_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\grok-3_mas_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\grok-3_mas_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\grok-3_mas_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\grok-3_mas_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\mistral-medium_mas_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\mistral-medium_mas_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\mistral-medium_mas_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\mistral-medium_mas_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\mistral-medium_mas_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-base\mistral-medium_mas_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\gpt-4o_mas_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\gpt-4o_mas_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\gpt-4o_mas_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\gpt-4o_mas_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\grok-3_mas_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\grok-3_mas_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\grok-3_mas_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\grok-3_mas_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\mistral-medium_mas_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\mistral-medium_mas_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\mistral-medium_mas_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas\mistral-medium_mas_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\gpt-4o_mas_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\gpt-4o_mas_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\gpt-4o_mas_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\gpt-4o_mas_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\gpt-4o_mas_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\gpt-4o_mas_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\grok-3_mas_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\grok-3_mas_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\grok-3_mas_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\grok-3_mas_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\grok-3_mas_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\grok-3_mas_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\mistral-medium_mas_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\mistral-medium_mas_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\mistral-medium_mas_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\mistral-medium_mas_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\mistral-medium_mas_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas-to-mas_rag\mistral-medium_mas_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\gpt-4o_mas_rag_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\gpt-4o_mas_rag_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\gpt-4o_mas_rag_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\gpt-4o_mas_rag_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\gpt-4o_mas_rag_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\gpt-4o_mas_rag_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\grok-3_mas_rag_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\grok-3_mas_rag_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\grok-3_mas_rag_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\grok-3_mas_rag_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\grok-3_mas_rag_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\grok-3_mas_rag_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\mistral-medium_mas_rag_l__vs__gpt-4o_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\mistral-medium_mas_rag_l__vs__grok-3_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\mistral-medium_mas_rag_l__vs__mistral-medium_base_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\mistral-medium_mas_rag_r__vs__gpt-4o_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\mistral-medium_mas_rag_r__vs__grok-3_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-base\mistral-medium_mas_rag_r__vs__mistral-medium_base_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\gpt-4o_mas_rag_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\gpt-4o_mas_rag_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\gpt-4o_mas_rag_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\gpt-4o_mas_rag_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\gpt-4o_mas_rag_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\gpt-4o_mas_rag_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\grok-3_mas_rag_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\grok-3_mas_rag_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\grok-3_mas_rag_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\grok-3_mas_rag_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\grok-3_mas_rag_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\grok-3_mas_rag_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\mistral-medium_mas_rag_l__vs__gpt-4o_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\mistral-medium_mas_rag_l__vs__grok-3_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\mistral-medium_mas_rag_l__vs__mistral-medium_mas_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\mistral-medium_mas_rag_r__vs__gpt-4o_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\mistral-medium_mas_rag_r__vs__grok-3_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas\mistral-medium_mas_rag_r__vs__mistral-medium_mas_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\gpt-4o_mas_rag_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\gpt-4o_mas_rag_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\gpt-4o_mas_rag_r__vs__grok-3_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\gpt-4o_mas_rag_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\grok-3_mas_rag_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\grok-3_mas_rag_l__vs__mistral-medium_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\grok-3_mas_rag_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\grok-3_mas_rag_r__vs__mistral-medium_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\mistral-medium_mas_rag_l__vs__gpt-4o_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\mistral-medium_mas_rag_l__vs__grok-3_mas_rag_r.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\mistral-medium_mas_rag_r__vs__gpt-4o_mas_rag_l.json
..\persuasio\persuasio\outputs\dialogues\mas_rag-to-mas_rag\mistral-medium_mas_rag_r__vs__grok-3_mas_rag_l.json

144

In [23]:
m2m_df = pd.DataFrame(m2m_debates)

m2m_df.head()

,loser,winner,session_id,debate_topic,next_speaker,first_speaker,second_speaker,current_speaker,dialogue_history,human_model_name,...,first_speaker_number_of_vector_based_rag_examples,second_speaker_utterance_with_corresponding_types,second_speaker_number_of_vector_based_rag_examples,utterance_classification_number_of_classifications,first_speaker_knowledge_base_ensemble_or_model_name,second_speaker_knowledge_base_ensemble_or_model_name,second_speaker_vector_based_persona_string,second_speaker_vector_based_persona_sys_prompt,first_speaker_vector_based_persona_sys_prompt,first_speaker_vector_based_persona_string
0,None,None,gpt-4o_base:l__vs__grok-3_base:r,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,grok-3_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'timestamp': '2025...",,...,100,"[[___Claim___, I’m not sold on that.], [___Cla...",100,1,,,NaN,NaN,NaN,NaN
1,None,None,gpt-4o_base:l__vs__mistral-medium_base:r,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,mistral-medium_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'timestamp': '2025...",,...,100,"[[___Claim___, The NHS's size leads to ineffic...",100,1,,,NaN,NaN,NaN,NaN
2,grok-3_base,gpt-4o_base,gpt-4o_base:r__vs__grok-3_base:l,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,grok-3_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'sentences_with_ut...",,...,100,"[[___Concede___, I’m not saying government sys...",100,1,,,NaN,NaN,NaN,NaN
3,None,None,gpt-4o_base:r__vs__mistral-medium_base:l,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,mistral-medium_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'timestamp': '2025...",,...,100,"[[___Claim___, Subsidies and tiered pricing ar...",100,1,,,NaN,NaN,NaN,NaN
4,None,None,grok-3_base:l__vs__gpt-4o_base:r,Debate the trade-offs of government interventi...,second_speaker,grok-3_base,gpt-4o_base,first_speaker,"[{'speaker': 'grok-3_base', 'timestamp': '2025...",,...,100,"[[___Since___, Regulation and subsidies can st...",100,1,,,NaN,NaN,NaN,NaN

In [24]:
m2m_df.drop(labels=["first_speaker_vector_based_persona_sys_prompt", "second_speaker_vector_based_persona_sys_prompt", 
                    "first_speaker_graph_rag_examples", "second_speaker_graph_rag_examples", 
                    "first_speaker_vector_based_persona_string", "second_speaker_vector_based_persona_string",
                    "first_speaker_intermediate_generations", "second_speaker_intermediate_generations"],
                    axis=1,
            inplace=True)

In [25]:
len(m2m_df)

144

In [26]:
save_m2m_debates = save_path / "model2model-debates.csv"
m2m_df.to_csv(save_m2m_debates, sep="|")

# Saving all debates together

In [27]:
all_data = [*m2m_debates, *h2m_processed_data]

In [28]:
len(all_data)

192

In [29]:
all_data[0]

{'loser': 'None',
 'winner': 'None',
 'session_id': 'gpt-4o_base:l__vs__grok-3_base:r',
 'debate_topic': 'Debate the trade-offs of government intervention across a range of issues, including healthcare, immigration, and welfare.',
 'next_speaker': 'second_speaker',
 'first_speaker': 'gpt-4o_base',
 'second_speaker': 'grok-3_base',
 'current_speaker': 'first_speaker',
 'dialogue_history': [{'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:07:29',
   'sentences_no_utterance_types': 'Government intervention is essential in healthcare, immigration, and welfare to ensure fairness and protect the most vulnerable in society.',
   'sentences_with_utterance_types': [['___Claim___',
     'Government intervention is essential in healthcare, immigration, and welfare to ensure fairness and protect the most vulnerable in society.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:07:38',
   'sentences_no_utterance_types': 'I disagree completely. Government intervention in healthcare, immigration, and welfare often creates more problems than it solves by stifling personal responsibility and economic freedom. Over-reliance on the state leads to inefficiency and bloated bureaucracies that waste taxpayer money. Why do you think the government can manage these areas better than individuals or private entities?',
   'sentences_with_utterance_types': [['___Claim___',
     'I disagree completely.'],
    ['___Claim___',
     'Government intervention in healthcare, immigration, and welfare often creates more problems than it solves by stifling personal responsibility and economic freedom.'],
    ['___Claim___',
     'Over-reliance on the state leads to inefficiency and bloated bureaucracies that waste taxpayer money.'],
    ['___Why___',
     'Why do you think the government can manage these areas better than individuals or private entities?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:07:44',
   'sentences_no_utterance_types': 'Government intervention can manage these areas better since it ensures that essential services like healthcare and welfare are accessible to everyone, regardless of income or status. Private entities prioritise profit, which often leads to inequality and exclusion of the most vulnerable. Immigration policies managed by the government can address labour shortages and contribute to economic growth while maintaining fairness. Without government oversight, the market fails to address systemic issues like poverty and health disparities. Relying solely on individuals or private entities risks leaving too many people behind.',
   'sentences_with_utterance_types': [['___Since___',
     'Government intervention can manage these areas better since it ensures that essential services like healthcare and welfare are accessible to everyone, regardless of income or status.'],
    ['___Since___',
     'Private entities prioritise profit, which often leads to inequality and exclusion of the most vulnerable.'],
    ['___Since___',
     'Immigration policies managed by the government can address labour shortages and contribute to economic growth while maintaining fairness.'],
    ['___Since___',
     'Without government oversight, the market fails to address systemic issues like poverty and health disparities.'],
    ['___Claim___',
     'Relying solely on individuals or private entities risks leaving too many people behind.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:07:55',
   'sentences_no_utterance_types': 'I’m not convinced. Government intervention might aim for fairness, but it often ends up creating dependency and inefficiency. Private entities, driven by competition, can deliver better results in healthcare and welfare if we let the market work. On immigration, government meddling usually leads to red tape that stifles economic growth rather than supports it. Why do you think a bloated bureaucracy can solve systemic issues better than individual initiative and market solutions?',
   'sentences_with_utterance_types': [['___Claim___', 'I’m not convinced.'],
    ['___Claim___',
     'Government intervention might aim for fairness, but it often ends up creating dependency and inefficiency.'],
    ['___Claim___',
     'Private entities, driven by competition, can deliver better results in healthcare and welfare if we let the market work.'],
    ['___Claim___',
     'On immigration, government meddling usually leads to red tape that stifles economic growth rather than supports it.'],
    ['___Why___',
     'Why do you think a bloated bureaucracy can solve systemic issues better than individual initiative and market solutions?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:08:01',
   'sentences_no_utterance_types': 'Government intervention solves systemic issues better since individual initiative and market solutions often prioritise profit over people. Essential services like healthcare and welfare cannot rely on competition alone because it leads to inequality and neglect of the vulnerable. Bureaucracy may have inefficiencies, but it ensures accountability and fairness, which the market fails to provide. Immigration policies need government oversight to balance economic growth with social cohesion, something private entities cannot achieve. Without intervention, systemic issues like poverty and health disparities persist unchecked.',
   'sentences_with_utterance_types': [['___Since___',
     'Government intervention solves systemic issues better since individual initiative and market solutions often prioritise profit over people.'],
    ['___Claim___',
     'Essential services like healthcare and welfare cannot rely on competition alone because it leads to inequality and neglect of the vulnerable.'],
    ['___Claim___',
     'Bureaucracy may have inefficiencies, but it ensures accountability and fairness, which the market fails to provide.'],
    ['___Claim___',
     'Immigration policies need government oversight to balance economic growth with social cohesion, something private entities cannot achieve.'],
    ['___Claim___',
     'Without intervention, systemic issues like poverty and health disparities persist unchecked.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:08:13',
   'sentences_no_utterance_types': 'I’m not buying it. Government intervention might claim to ensure fairness, but it often just creates a nanny state that kills off personal responsibility. Markets aren’t perfect, yet they drive innovation and efficiency in healthcare and welfare far better than any bureaucracy. On immigration, government oversight usually means endless rules that choke economic growth instead of balancing anything. Why do you think a slow, wasteful system can tackle poverty or health disparities better than empowering individuals and businesses?',
   'sentences_with_utterance_types': [['___Claim___', 'I’m not buying it.'],
    ['___Claim___',
     'Government intervention might claim to ensure fairness, but it often just creates a nanny state that kills off personal responsibility.'],
    ['___Claim___',
     'Markets aren’t perfect, yet they drive innovation and efficiency in healthcare and welfare far better than any bureaucracy.'],
    ['___Claim___',
     'On immigration, government oversight usually means endless rules that choke economic growth instead of balancing anything.'],
    ['___Why___',
     'Why do you think a slow, wasteful system can tackle poverty or health disparities better than empowering individuals and businesses?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:08:19',
   'sentences_no_utterance_types': 'Government intervention tackles poverty and health disparities better since empowering individuals and businesses alone often leads to neglect of those who cannot compete in the market. Essential services like healthcare and welfare require a safety net that only government can provide to ensure no one is left behind. While markets drive innovation, they also create inequality and exclude the most vulnerable. Immigration policies need structured oversight to balance economic growth with social cohesion, which private entities cannot achieve. A slow system may have inefficiencies, but it ensures fairness and accountability, which are crucial for addressing systemic issues.',
   'sentences_with_utterance_types': [['___Since___',
     'Government intervention tackles poverty and health disparities better since empowering individuals and businesses alone often leads to neglect of those who cannot compete in the market.'],
    ['___Claim___',
     'Essential services like healthcare and welfare require a safety net that only government can provide to ensure no one is left behind.'],
    ['___Claim___',
     'While markets drive innovation, they also create inequality and exclude the most vulnerable.'],
    ['___Since___',
     'Immigration policies need structured oversight to balance economic growth with social cohesion, which private entities cannot achieve.'],
    ['___Since___',
     'A slow system may have inefficiencies, but it ensures fairness and accountability, which are crucial for addressing systemic issues.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:08:32',
   'sentences_no_utterance_types': 'I’m not sold on that. Government intervention might promise a safety net, yet it often traps people in dependency and wastes resources on red tape. Markets may create inequality, yet they also reward hard work and innovation, which lifts more people out of poverty than any state handout. On immigration, government oversight just bogs everything down with rules, while private solutions could adapt faster to economic needs. Why do you think a clunky, inefficient system is better than trusting people and businesses to sort things out?',
   'sentences_with_utterance_types': [['___Claim___', 'I’m not sold on that.'],
    ['___Claim___',
     'Government intervention might promise a safety net, yet it often traps people in dependency and wastes resources on red tape.'],
    ['___Claim___',
     'Markets may create inequality, yet they also reward hard work and innovation, which lifts more people out of poverty than any state handout.'],
    ['___Claim___',
     'On immigration, government oversight just bogs everything down with rules, while private solutions could adapt faster to economic needs.'],
    ['___Why___',
     'Why do you think a clunky, inefficient system is better than trusting people and businesses to sort things out?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:08:38',
   'sentences_no_utterance_types': 'A clunky system is better because it prioritises fairness and accountability, which markets and private entities often fail to deliver. Trusting people and businesses alone leads to inequality and neglect of those who cannot compete, leaving them without essential services like healthcare and welfare. Government intervention ensures a safety net that prevents people from falling through the cracks, addressing systemic issues like poverty and health disparities. Immigration policies need structured oversight to balance economic growth with social cohesion, something private solutions cannot achieve. Without intervention, the most vulnerable are left behind, and systemic problems persist unchecked.',
   'sentences_with_utterance_types': [['___Since___',
     'A clunky system is better because it prioritises fairness and accountability, which markets and private entities often fail to deliver.'],
    ['___Claim___',
     'Trusting people and businesses alone leads to inequality and neglect of those who cannot compete, leaving them without essential services like healthcare and welfare.'],
    ['___Since___',
     'Government intervention ensures a safety net that prevents people from falling through the cracks, addressing systemic issues like poverty and health disparities.'],
    ['___Since___',
     'Immigration policies need structured oversight to balance economic growth with social cohesion, something private solutions cannot achieve.'],
    ['___Claim___',
     'Without intervention, the most vulnerable are left behind, and systemic problems persist unchecked.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:08:50',
   'sentences_no_utterance_types': 'I’m not convinced at all. Government intervention might aim for fairness, yet it often just breeds dependency and wastes money on endless bureaucracy. Markets aren’t flawless, yet they drive innovation and reward effort, which does more to tackle poverty than any state safety net. On immigration, private solutions can respond to economic needs far quicker than clunky government rules. Why do you think a slow, inefficient system can genuinely protect the vulnerable better than empowering individuals and businesses?',
   'sentences_with_utterance_types': [['___Claim___',
     'I’m not convinced at all.'],
    ['___Claim___',
     'Government intervention might aim for fairness, yet it often just breeds dependency and wastes money on endless bureaucracy.'],
    ['___Claim___',
     'Markets aren’t flawless, yet they drive innovation and reward effort, which does more to tackle poverty than any state safety net.'],
    ['___Claim___',
     'On immigration, private solutions can respond to economic needs far quicker than clunky government rules.'],
    ['___Why___',
     'Why do you think a slow, inefficient system can genuinely protect the vulnerable better than empowering individuals and businesses?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:08:55',
   'sentences_no_utterance_types': 'A slow system protects the vulnerable better because it prioritises fairness and ensures no one is left behind. Empowering individuals and businesses alone leads to inequality and neglect of those who cannot compete in the market. Essential services like healthcare and welfare need government oversight to provide a safety net that markets fail to deliver. Immigration policies require structured oversight to balance economic growth with social cohesion, which private solutions cannot achieve. Without intervention, systemic issues like poverty and health disparities persist unchecked, leaving the most vulnerable to suffer.',
   'sentences_with_utterance_types': [['___Since___',
     'A slow system protects the vulnerable better because it prioritises fairness and ensures no one is left behind.'],
    ['___Claim___',
     'Empowering individuals and businesses alone leads to inequality and neglect of those who cannot compete in the market.'],
    ['___Claim___',
     'Essential services like healthcare and welfare need government oversight to provide a safety net that markets fail to deliver.'],
    ['___Claim___',
     'Immigration policies require structured oversight to balance economic growth with social cohesion, which private solutions cannot achieve.'],
    ['___Since___',
     'Without intervention, systemic issues like poverty and health disparities persist unchecked, leaving the most vulnerable to suffer.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:09:06',
   'sentences_no_utterance_types': 'I’m not buying this. A slow system might claim to prioritise fairness, yet it often just mires everyone in red tape and kills off personal drive. Markets aren’t perfect, yet they spur innovation and reward grit, which pulls more people up than any government safety net. On immigration, private solutions can adapt to economic needs way faster than any state oversight. Why do you think a sluggish, wasteful setup can truly help the vulnerable more than trusting people and businesses to step up?',
   'sentences_with_utterance_types': [['___Claim___', 'I’m not buying this.'],
    ['___Claim___',
     'A slow system might claim to prioritise fairness, yet it often just mires everyone in red tape and kills off personal drive.'],
    ['___Claim___',
     'Markets aren’t perfect, yet they spur innovation and reward grit, which pulls more people up than any government safety net.'],
    ['___Claim___',
     'On immigration, private solutions can adapt to economic needs way faster than any state oversight.'],
    ['___Why___',
     'Why do you think a sluggish, wasteful setup can truly help the vulnerable more than trusting people and businesses to step up?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:09:12',
   'sentences_no_utterance_types': 'A sluggish setup helps the vulnerable more because it ensures fairness and accountability, which markets and private entities often overlook. Trusting people and businesses alone leads to inequality and neglect of those who cannot compete, leaving them without essential services like healthcare and welfare. Government oversight provides a safety net that prevents systemic issues like poverty and health disparities from worsening. Immigration policies need structured oversight to balance economic growth with social cohesion, which private solutions cannot guarantee. Without intervention, the most vulnerable are left behind, and systemic problems remain unaddressed.',
   'sentences_with_utterance_types': [['___Since___',
     'A sluggish setup helps the vulnerable more because it ensures fairness and accountability, which markets and private entities often overlook.'],
    ['___Claim___',
     'Trusting people and businesses alone leads to inequality and neglect of those who cannot compete, leaving them without essential services like healthcare and welfare.'],
    ['___Claim___',
     'Government oversight provides a safety net that prevents systemic issues like poverty and health disparities from worsening.'],
    ['___Claim___',
     'Immigration policies need structured oversight to balance economic growth with social cohesion, which private solutions cannot guarantee.'],
    ['___Claim___',
     'Without intervention, the most vulnerable are left behind, and systemic problems remain unaddressed.']]},
  {'speaker': 'grok-3_base',
   'timestamp': '2025-10-04 04:09:24',
   'sentences_no_utterance_types': 'I’m not sold on that. A sluggish setup might aim for fairness, yet it often just bogs everyone down with inefficiency and kills off personal responsibility. Markets may not be perfect, yet they drive innovation and reward hard work, which helps more people escape poverty than any government scheme. On immigration, private solutions can react to economic needs much faster than state meddling. Why do you think a wasteful, slow system can really do more for the vulnerable than empowering individuals and businesses?',
   'sentences_with_utterance_types': [['___Claim___', 'I’m not sold on that.'],
    ['___Claim___',
     'A sluggish setup might aim for fairness, yet it often just bogs everyone down with inefficiency and kills off personal responsibility.'],
    ['___Claim___',
     'Markets may not be perfect, yet they drive innovation and reward hard work, which helps more people escape poverty than any government scheme.'],
    ['___Claim___',
     'On immigration, private solutions can react to economic needs much faster than state meddling.'],
    ['___Why___',
     'Why do you think a wasteful, slow system can really do more for the vulnerable than empowering individuals and businesses?']]},
  {'speaker': 'gpt-4o_base',
   'timestamp': '2025-10-04 04:09:29',

In [30]:
all_df = pd.DataFrame(all_data)

In [31]:
all_df.head()

,loser,winner,session_id,debate_topic,next_speaker,first_speaker,second_speaker,current_speaker,dialogue_history,human_model_name,...,max_sentences,speaker_order,original_claim,opponents_utterance,opponent_speaker_name,opponents_commitments,opponents_original_claim,utterance_with_corresponding_types,typical_replies_for_last_speakers_response,opponents_utterance_with_corresponding_types
0,None,None,gpt-4o_base:l__vs__grok-3_base:r,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,grok-3_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'timestamp': '2025...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,None,None,gpt-4o_base:l__vs__mistral-medium_base:r,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,mistral-medium_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'timestamp': '2025...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,grok-3_base,gpt-4o_base,gpt-4o_base:r__vs__grok-3_base:l,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,grok-3_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'sentences_with_ut...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,None,None,gpt-4o_base:r__vs__mistral-medium_base:l,Debate the trade-offs of government interventi...,second_speaker,gpt-4o_base,mistral-medium_base,first_speaker,"[{'speaker': 'gpt-4o_base', 'timestamp': '2025...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,None,None,grok-3_base:l__vs__gpt-4o_base:r,Debate the trade-offs of government interventi...,second_speaker,grok-3_base,gpt-4o_base,first_speaker,"[{'speaker': 'grok-3_base', 'timestamp': '2025...",,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
all_df.drop(labels=["first_speaker_vector_based_persona_sys_prompt", "second_speaker_vector_based_persona_sys_prompt", 
                    "first_speaker_graph_rag_examples", "second_speaker_graph_rag_examples", 
                    "first_speaker_vector_based_persona_string", "second_speaker_vector_based_persona_string",
                    "first_speaker_intermediate_generations", "second_speaker_intermediate_generations"],
                    axis=1,
            inplace=True)

In [33]:
all_df["first_speaker_political_position_range"]

0      20:40
1      20:40
2      60:80
3      60:80
4      20:40
       ...
187    60:80
188    20:40
189    20:40
190    20:40
191    20:40
Name: first_speaker_political_position_range, Length: 192, dtype: object

In [34]:
save_all_data = save_path / "all-debates.csv"
all_df.to_csv(save_all_data, sep="|")

In [39]:
models = ["gpt-4o", "grok-3", "mistral-medium"]
agent_variants = ["_base", "_mas", "_mas_rag"]

models_and_variants = [models[x] + agent_variants[y] for x in range(len(models)) for y in range(len(agent_variants))]

print(models_and_variants)

m2m_dialogue_count = 0
h2m_dialogue_count = 0
h2h_dialogue_count = 0

for idx, row in all_df.iterrows():
    if row["first_speaker"] in models_and_variants and row["second_speaker"] in models_and_variants:
        m2m_dialogue_count += 1

    elif row["first_speaker"] in models_and_variants and row["second_speaker"] not in models_and_variants:
        h2m_dialogue_count += 1

    elif row["first_speaker"] not in models_and_variants and row["second_speaker"] not in models_and_variants:  
        h2m_dialogue_count += 1
    else:
        h2h_dialogue_count += 1

['gpt-4o_base', 'gpt-4o_mas', 'gpt-4o_mas_rag', 'grok-3_base', 'grok-3_mas', 'grok-3_mas_rag', 'mistral-medium_base', 'mistral-medium_mas', 'mistral-medium_mas_rag']

In [40]:
print(m2m_dialogue_count) 
print(h2m_dialogue_count) 
print(h2h_dialogue_count)

144
36
12