In [1]:
import pandas as pd
import os

import warnings
warnings.filterwarnings("ignore")

from prolific import ProlificAPIError, ProlificClient

pd.set_option('display.max_columns', None)

client = ProlificClient(
    api_token=os.environ["prolific_key"])

In [2]:
demographic_df = pd.read_csv("data/prolific_demographic_export_698efef38f6dc0baf73e7f6f.csv")

In [3]:
demographic_df.head()

,Submission id,Age,Archived at,Company type,Completed at,Completion code,Country of birth,Country of residence,Custom study tncs accepted at,Degree subject,Employment sector,Employment status,Ethnicity,Ethnicity simplified,Fluent languages,Function in organisation,Gender,Highest education level completed,Industry,Language,Language related disorders,Literacy difficulties,Nationality,Organisational tenure,Participant id,Place of most time spent before turning eighteen,Political affiliation (uk),Primary language,Reviewed at,Sex,Started at,Status,Student status,Time taken,Total approvals,URL,Work function,Work role,Years of management experience,Years of work experience
0,698eff4de8cf64672154b3a0,37,2026-02-13T10:45:04.768841Z,NaN,2026-02-13T10:45:04.429000Z,NOCODE,United Kingdom,United Kingdom,Not Applicable,NaN,NaN,Full-Time,NaN,White,NaN,NaN,NaN,Undergraduate degree (BA/BSc/other),NaN,English,NaN,NaN,United Kingdom,NaN,59e7232f24d7bf00012f112e,NaN,Centre,NaN,NaN,Male,2026-02-13T10:39:17.481000Z,AWAITING REVIEW,No,347.0,6695,https://app.prolific.com/data-collection-tool/...,NaN,NaN,NaN,NaN
1,698eff5095bdd7ccac0100eb,41,2026-02-13T10:44:40.354480Z,NaN,2026-02-13T10:44:40.027000Z,NOCODE,United Kingdom,United Kingdom,Not Applicable,NaN,NaN,"Not in paid work (e.g. homemaker', 'retired or...",NaN,Asian,NaN,NaN,NaN,Undergraduate degree (BA/BSc/other),NaN,English,NaN,NaN,United Kingdom,NaN,6048c1da4fb34916883f2e7d,NaN,Left,NaN,NaN,Female,2026-02-13T10:39:42.657000Z,AWAITING REVIEW,No,298.0,2168,https://app.prolific.com/data-collection-tool/...,NaN,NaN,NaN,NaN
2,698eff51040e66330d7e4720,25,2026-02-13T10:43:46.841981Z,NaN,2026-02-13T10:43:46.503000Z,NOCODE,United Kingdom,United Kingdom,Not Applicable,NaN,NaN,Full-Time,NaN,Mixed,NaN,NaN,NaN,Undergraduate degree (BA/BSc/other),NaN,English,NaN,NaN,United Kingdom,NaN,66cb2e0bd2169db778550269,NaN,Centre,NaN,NaN,Male,2026-02-13T10:39:17.227000Z,AWAITING REVIEW,No,270.0,5562,https://app.prolific.com/data-collection-tool/...,NaN,NaN,NaN,NaN
3,698eff518fe50e7f1d474cfc,CONSENT_REVOKED,2026-02-23T09:42:23.694827Z,CONSENT_REVOKED,NaN,NaN,CONSENT_REVOKED,CONSENT_REVOKED,Not Applicable,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,5fb23ca83dd5537b40fbef87,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,NaN,CONSENT_REVOKED,2026-02-13T10:39:17.892000Z,RETURNED,CONSENT_REVOKED,NaN,3562,NaN,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED,CONSENT_REVOKED
4,698eff525b0d9f1b15aee93a,41,2026-02-13T10:44:21.790958Z,NaN,2026-02-13T10:44:21.446000Z,NOCODE,United Kingdom,United Kingdom,Not Applicable,NaN,NaN,Full-Time,NaN,White,NaN,NaN,NaN,Graduate degree (MA/MSc/MPhil/other),NaN,English,NaN,NaN,United Kingdom,NaN,60537fdcda0ac05f1c59c57f,NaN,Left,NaN,NaN,Female,2026-02-13T10:39:27.732000Z,AWAITING REVIEW,Yes,294.0,4763,https://app.prolific.com/data-collection-tool/...,NaN,NaN,NaN,NaN

In [4]:
demographic_df.columns

Index(['Submission id', 'Age', 'Archived at', 'Company type', 'Completed at',
       'Completion code', 'Country of birth', 'Country of residence',
       'Custom study tncs accepted at', 'Degree subject', 'Employment sector',
       'Employment status', 'Ethnicity', 'Ethnicity simplified',
       'Fluent languages', 'Function in organisation', 'Gender',
       'Highest education level completed', 'Industry', 'Language',
       'Language related disorders', 'Literacy difficulties', 'Nationality',
       'Organisational tenure', 'Participant id',
       'Place of most time spent before turning eighteen',
       'Political affiliation (uk)', 'Primary language', 'Reviewed at', 'Sex',
       'Started at', 'Status', 'Student status', 'Time taken',
       'Total approvals', 'URL', 'Work function', 'Work role',
       'Years of management experience', 'Years of work experience'],
      dtype='str')

In [5]:
left_pol_aff_df = demographic_df[demographic_df["Political affiliation (uk)"] == "Left"]
centre_pol_aff_df = demographic_df[demographic_df["Political affiliation (uk)"] == "Centre"]
right_pol_aff_df = demographic_df[demographic_df["Political affiliation (uk)"] == "Right"]

In [6]:
len(left_pol_aff_df)

1613

In [7]:
len(centre_pol_aff_df)

1214

In [8]:
len(right_pol_aff_df)

450

In [9]:
demographic_df["Sex"].unique()

<StringArray>
['Male', 'Female', 'CONSENT_REVOKED', 'Prefer not to say']
Length: 4, dtype: str

In [10]:
male_df = demographic_df[demographic_df["Sex"] == "Male"]
female_df = demographic_df[demographic_df["Sex"] == "Female"]

In [11]:
len(male_df)

1376

In [12]:
len(female_df)

1896

In [13]:
# Define age bins and labels
bins = [0, 25, 35, 45, 55, 65, 100]
labels = ["18-25", "26-35", "36-45", "46-55", "56-65", "65+"]
bins = [0, 30, 40, 50, 60, 70, 100]
labels = ["18-30", "31-40", "41-50", "51-60", "61-70", "70+"]

demographic_df["Age"] = pd.to_numeric(demographic_df["Age"], errors="coerce")
demographic_df["Age_Group"] = pd.cut(demographic_df["Age"], bins=bins, labels=labels, right=True)

# Create subgroup DataFrames per age group
age_group_dfs = {}
for label in labels:
    age_group_dfs[label] = demographic_df[demographic_df["Age_Group"] == label]
    print(f"{label}: {len(age_group_dfs[label])} participants")

18-30: 784 participants
31-40: 995 participants
41-50: 692 participants
51-60: 482 participants
61-70: 267 participants
70+: 59 participants

In [14]:
subjective_df = pd.read_csv("data/subjective-persuasiveness-prolific-results.csv", sep="|")
logical_df = pd.read_csv("data/all-debates.csv", sep="|")

In [15]:
ID = "698efef38f6dc0baf73e7f6f"

client.get_study(ID)

{'id': '698efef38f6dc0baf73e7f6f',
 'name': 'Evaluating the Persuasiveness of Debaters',
 'description': '<p>In this study, you will evaluate <strong>persuasiveness in debate transcripts</strong>. You will read transcripts from <strong>two separate debates</strong> on the same topic and judge which speaker is more persuasive.</p><p>Each debate features two participants, Speaker A and Speaker B. Although the debates involve different individuals, <strong>Speaker A represents the same ideological or political position in both debates</strong>.</p><p>Your task is to compare the persuasiveness of <strong>Speaker A across the two debates</strong>, focusing only on how effectively they argue their position.</p><p>There are <strong>no right or wrong answers</strong>! We are interested in your honest, subjective judgment based on the debate content.</p><p></p>',
 'total_available_places': 3234,
 'reward': 120,
 'average_reward_per_hour': 1155.0,
 'external_study_url': 'https://tars.dcp.prod.aws.prolific.co/access-details/86e0d8b3-e084-489b-b3a9-a6d9a14128bf/allocate',
 'video_platform': None,
 'video_id': None,
 'device_compatibility': ['desktop', 'mobile', 'tablet'],
 'peripheral_requirements': [],
 'researcher': {'id': '693837451402cb5f5765430f',
  'name': 'Jordan Robinson',
  'email': 'j.robinson@turing.ac.uk',
  'country': 'GB',
  'institution': {'name': 'turing.ac.uk',
   'logo': 'https://internal-api.prolific.com/assets/img/institutions/turing.ac.uk.png',
   'link': 'http://www.turing.ac.uk'}},
 'publisher': {'id': '693837451402cb5f5765430f',
  'name': 'Jordan Robinson',
  'email': 'j.robinson@turing.ac.uk',
  'country': 'GB',
  'institution': {'name': 'turing.ac.uk',
   'logo': 'https://internal-api.prolific.com/assets/img/institutions/turing.ac.uk.png',
   'link': 'http://www.turing.ac.uk'}},
 'places_taken': 3234,
 'study_type': 'SINGLE',
 'submissions_config': {'max_submissions_per_participant': 1,
  'max_concurrent_submissions': -1,
  'auto_rejection_categories': ['EXCEPTIONALLY_FAST']},
 'status': 'AWAITING REVIEW',
 'internal_name': 'final_full_3_annotations_per_human_with_2_atten_checks',
 'minimum_reward_per_hour': 600.0,
 'date_created': '2026-02-13T10:37:30.850000Z',
 'published_at': '2026-02-13T10:38:17.050000Z',
 'number_of_submissions': 3536,
 'estimated_completion_time': 8,
 'average_time_taken': 6,
 'average_time_taken_seconds': 374,
 'completion_code': None,
 'failed_attention_code': None,
 'alternative_completion_codes': [],
 'completion_code_action': None,
 'last_email_update_sent_datetime': None,
 'maximum_allowed_time': 39,
 'receipt': None,
 'eligible_participant_count': 6728,
 'total_participant_pool': 216534,
 'currency_code': 'GBP',
 'total_cost': 543312,
 'fees_per_submission': 0.0,
 'fees_percentage': 0.333333,
 'service_margin_percentage': '0.25000000000000000',
 'vat_percentage': 0.2,
 'discount_from_coupons': 0,
 'estimated_reward_per_hour': 900.0,
 'representative_sample': None,
 'publish_at': None,
 'prolific_id_option': None,
 'is_underpaying': None,
 'average_reward_per_hour_without_adjustment': 1155.0,
 'has_had_adjustment': False,
 'reward_level': {'below_prolific_min': None, 'below_original_estimate': None},
 'project': '6978d3c3aa58c1adeeb3f465',
 'workspace': '688784736462d228c69fdd63',
 'naivety_distribution_rate': -1,
 'is_reallocated': False,
 'external_app': None,
 'external_id': None,
 'privacy_notice': None,
 'can_be_reallocated': False,
 'reallocated_places': 0,
 'progress_percentage': 100,
 'completion_codes': [{'code': 'C815J9E9',
   'code_type': 'COMPLETED',
   'actions': [{'action': 'MANUALLY_REVIEW'}],
   'actor': 'participant'}],
 'metadata': None,
 'filter_set_id': None,
 'filter_set_version': None,
 'filters': [{'filter_id': 'current-country-of-residence',
   'selected_values': ['0']},
  {'filter_id': 'highest-education-level-completed',
   'selected_values': ['4', '5', '6']},
  {'filter_id': 'political-affiliation-uk',
   'selected_values': ['0', '1', '2']}],
 'has_credentials': False,
 'credential_pool_id': None,
 'access_details_collection_id': '86e0d8b3-e084-489b-b3a9-a6d9a14128bf',
 'access_details': [{'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/001fa3b4-68fe-5531-afc9-1aaf675477a3',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/005ae885-bd1e-51c8-8975-9a65f0b12637',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/00826f1b-a5b6-51a1-9306-dcf980416e70',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/00882ffe-0cf2-5fd6-b879-a1fafd988863',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0144426b-eb27-5790-8cad-87e8cd867bef',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01caa0f1-05c6-5ee1-a8f2-54187eb271eb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01ddd2c0-00ba-542e-9986-2b5559bf8653',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01f2b42a-ba00-5246-8290-bfb854e7a2d7',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/01f978f9-f310-5c2f-8ec2-726104ddd451',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/020f79c1-50f0-5dec-b178-82e816efa973',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/024a21d2-4ada-527f-bdf2-50de33d60183',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0317b707-e0b0-5b47-950c-9d4ef6c6257a',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0393a2a6-105a-5bfc-8dc8-03eddb36c0c8',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/03ccf60f-9d2b-5cfa-8cce-6db22eb96d53',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/03f6c707-10ec-5e7c-836d-ce7e5c514953',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/03fd2089-1ed5-5664-871b-7e870bc0f94b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/05406f80-716c-5f32-9b3e-0a1240f036ec',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/06a4ce37-bc65-53f4-90cc-75cddbe52a39',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/06caab5a-a713-55ff-83b2-054e2aeb9e64',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/06d28d8b-c36b-52c1-8a6b-88bb810b44d0',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/07ad69c4-3fed-55b1-9586-1647d44ab3f2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/07da7713-5895-5c72-8e9c-5ce980653c8b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/082a3825-7238-55cd-b12f-0c0a5de492af',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/088e1a8d-02dd-5ae7-967d-c64d7fc61e9d',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/091ad7ce-5f5e-5d70-8274-54fa7a0a835d',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/091b4e41-0d8c-5c7d-87c7-a9b2c9976dcc',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/093ca67b-1f39-5bd8-a82f-7e0d0fe9b0f2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0a1e9d80-47b0-5362-b477-096833407e5b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0a338905-6658-54fd-96b4-18be79a20488',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0ae33930-091e-5a07-a34b-e1a07b5e9816',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0b730dcf-9168-50f2-a8ab-3489f31baadb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0c0032eb-0be1-5291-8302-2bdf529441c5',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0d2fe138-c8d1-541a-a60a-f40824d1df54',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0f3c09b7-7ff1-5c37-ab4b-b04efcb0ef1d',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0f63aced-d2c5-5f4f-90bd-764159f21def',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0fa39bd4-b7f4-5743-a5d4-10ef22980cdb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/0fee8c0e-0763-5c7f-a810-a11d5f95d0dc',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/10ecdb91-d6a8-562e-8747-1a0ef13abb6b',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/11f1183c-9ce4-5d5a-b5a2-0b7fe0b58c91',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1233a0e6-ff40-5d3d-b841-a23b5df83ca1',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/12947010-3120-58a8-9fcf-bae8a718e292',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/129ab5f7-9abd-591b-ac44-4a65ead86627',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/132b843f-5d41-5a21-869b-a8f7dac017a9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1345e30c-213a-5d86-9b50-3ab9c6ae60ab',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/137d1f6a-d508-5646-812a-42d74df03bfd',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1537631d-fd29-5aea-8ae5-e717930c75eb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/15440d5d-b2b5-5589-ace3-15cf8e03b7d0',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1613e21a-88e5-5972-8c37-abb9adb466c2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/163101c2-70be-5a6b-a5a5-c8c2483930b5',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/163ba230-63c2-5d9e-b770-97c40afd016e',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/174d30ab-e300-523c-897e-25ee72724c58',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/178b14f0-ed94-572b-a46c-d182c682a8cb',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/17903436-07c7-5ef6-aa24-9b897fc76518',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/18bb773f-2d69-583a-a32a-28b4f1dbc980',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1912a09e-ee41-55a1-9aa4-3bf6f93808c6',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1a2683c7-566e-56e0-bb0c-7fac25cd91af',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1a7e9332-106d-5c41-b5b4-b51b01f842ed',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1a7f9613-81bf-5899-b973-80a0fdf217e8',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1aefbd4b-dfe1-582e-a5bd-cc0581f4f4a7',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1b49c192-c0bd-5a00-917b-8603a19c5e84',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1b64a51c-7060-5db8-b9aa-0192992bcdf5',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1c32aa99-cfc3-5043-9788-c9ed6647e3a7',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1c7274a5-65c0-5a5e-b99c-1b65be34f817',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1c9cdf10-23f7-54db-8774-008421d4f0d9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1ca838f8-5589-54a5-aad6-e1837911e301',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1dd7436b-2037-568d-9674-9d0b45747154',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1de9633f-2ad6-5c9b-b561-e9c0efd6c684',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1dfc82e4-05cc-5380-9a7c-f58386ac8388',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1eaef366-578f-5162-a9d7-cdc05c4d85f9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1ecdd0a6-eb46-5a80-8cce-116d50e3ba26',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1f62c780-f4a4-5ac2-9c87-acc9de7d2ef2',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1f806385-3aec-5004-9b1d-9fb5fca7a538',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/1f8a5bc9-7544-5cf2-b548-18a41616b495',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/20d889a6-a08b-55e5-9dee-56f38e96b1c9',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/22fed747-e728-5f61-8d58-681d876dcc38',
   'total_allocation': 7,
   'allocated': 7},
  {'external_url': 'https://app.prolific.com/data-collection-tool/batches/019c5684-e8e6-737c-9442-07692f856379/task-groups/23b58db6-af4b-5ded-94e9-baf691d9cfb4',
   'total_allocation': 7,
   'allocated': 7},

In [16]:
responses = client.list_submissions(study=ID, page_size=1000)

In [17]:
rejected = client.list_submissions(study=ID, page_size=1000, rejected=True)

In [18]:
df = pd.read_csv(
    "data/019c5684-e8e6-737c-9442-07692f856379.csv"
)

df = df[~df["Debate Topic"].str.contains("ATTENTION CHECK:", na=False)]

In [19]:
df.head()

,DataPoint_ID,Task_Group_ID,Task_Type,Question,Debate Topic,Debate 1,Debate 2,META_SAMPLE1_POLITICAL_POSITION,META_SAMPLE1_SPEAKERA,META_COMPARISONID_1,META_SAMPLE1_SPEAKERB,META_COMPARISON,META_TASK_GROUP_ID,META_COMPARISONID,META_ATTEN_CHECK_PERSUASIVENESS_ANSWER,META_ATTEN_CHECK_CONFIDENCE_ANSWER,META_SAMPLE1_DIALOGUE_CHUNK,META_PAIR_SESSION_IDS,META_SAMPLE2_POLITICAL_POSITION,Annotator1_ID,Annotator1_Response,Annotator1_Timestamp,Annotator2_ID,Annotator2_Response,Annotator2_Timestamp,Annotator3_ID,Annotator3_Response,Annotator3_Timestamp,Annotator4_ID,Annotator4_Response,Annotator4_Timestamp,Annotator5_ID,Annotator5_Response,Annotator5_Timestamp,Annotator6_ID,Annotator6_Response,Annotator6_Timestamp,Annotator7_ID,Annotator7_Response,Annotator7_Timestamp,Annotator8_ID,Annotator8_Response,Annotator8_Timestamp
0,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Speaker A from Debate 2,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Speaker A from Debate 1,2026-02-13T12:06:32.977Z,5e90781c06c6ee000974d087,Speaker A from Debate 1,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Speaker A from Debate 1,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Speaker A from Debate 1,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Speaker A from Debate 1,2026-02-18T22:06:51.931Z,5f0c94983314760efb2814c1,Speaker A from Debate 1,2026-02-21T11:14:56.612Z,NaN,NaN,NaN
1,019c5684-b730-70dd-b5f3-ca369d6a622c,412,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker A: ""How can this be done if the opport...","Speaker A: ""Would you concur that this point r...",left,human_9,1154,gpt-4o_base,"('human_9', 'human_11')",412,2064,NaN,NaN,"[{'speaker': 'human_9', 'timestamp': '2026-01-...","('XZV57F', 'OR2XBB')",left,6318acc6273e916b39a95a85,Neutral,2026-02-13T10:46:55.851Z,579f55486475d400015ab683,Somewhat confident,2026-02-13T12:06:32.978Z,5e90781c06c6ee000974d087,Very confident,2026-02-13T19:45:23.867Z,66066cf2a8876c1d1907732a,Somewhat unsure,2026-02-14T20:40:58.661Z,5d07689bad18d40001bb73c1,Neutral,2026-02-16T15:57:15.704Z,63d13c076dd249ca3a6bffbb,Very confident,2026-02-18T22:06:51.932Z,5f0c94983314760efb2814c1,Somewhat confident,2026-02-21T11:14:56.612Z,NaN,NaN,NaN
4,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,NaN,NaN,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,5dd9a7ff98981d926df9ea18,Speaker A from Debate 1,2026-02-13T10:45:34.049Z,6761658b4037ac25f8afbd22,Speaker A from Debate 1,2026-02-13T11:48:57.224Z,5e2c8f69cad44b2bc5ce9a34,Speaker A from Debate 1,2026-02-13T14:38:04.633Z,67605337c41b9ba5ae52a0c8,Speaker A from Debate 1,2026-02-13T21:03:16.757Z,673f069497dc06b5ecbf7470,Speaker A from Debate 1,2026-02-15T11:47:01.602Z,6658ed9e2802dccba9041ca4,Speaker A from Debate 1,2026-02-17T10:05:08.725Z,677d4d04da6aea9117c478b5,Speaker A from Debate 1,2026-02-20T11:56:31.327Z,NaN,NaN,NaN
5,019c5684-bc10-73fa-ae9c-bdda3c2e3812,417,multiple_choice,How confident are you in your choice?,Debate the trade-offs of government interventi...,"Speaker B: ""Market forces ensure that the best...","Speaker A: ""Government intervention in public ...",left,gpt-4o_mas_rag,763,mistral-medium_mas,"('gpt-4o_mas_rag', 'human_6')",417,2089,NaN,NaN,"[{'speaker': 'mistral-medium_mas', 'timestamp'...","('gpt-4o_mas_rag:l__vs__mistral-medium_mas:r',...",left,5dd9a7ff98981d926df9ea18,Very confident,2026-02-13T10:45:34.049Z,6761658b4037ac25f8afbd22,Somewhat confident,2026-02-13T11:48:57.224Z,5e2c8f69cad44b2bc5ce9a34,Somewhat confident,2026-02-13T14:38:04.633Z,67605337c41b9ba5ae52a0c8,Very confident,2026-02-13T21:03:16.757Z,673f069497dc06b5ecbf7470,Very confident,2026-02-15T11:47:01.602Z,6658ed9e2802dccba9041ca4,Very confident,2026-02-17T10:05:08.726Z,677d4d04da6aea9117c478b5,Very confident,2026-02-20T11:56:31.327Z,NaN,NaN,NaN
8,019c5683-7bc9-737c-98f5-9d58923d45e6,60,multiple_choice,"Based only on the debate transcripts, which Sp...",Debate the trade-offs of government interventi...,"Speaker A: ""Resentment and alienisation within...","Speaker A: ""Are taxes the only way to develop ...",right,human_6,988,grok-3_mas,"('human_6', 'human_12')",60,304,NaN,NaN,"[{'speaker': 'human_6', 'timestamp': '2026-01-...","('LU5JFB', 'VIJPFB')",right,5e908233a1ea4d013e973b75,Both Speaker As were equally persuasive,2026-02-13T11:15:52.377Z,653d14bc14d143d888af01b0,Speaker A from Debate 2,2026-02-13T13:26:19.093Z,67be393ad49f9deccf6ddd22,Speaker A from Debate 2,2026-02-13T17:26:28.900Z,5e64da5ac34e832466061bf8,Speaker A from Debate 2,2026-02-14T12:59:43.415Z,671f96e923e76ff949ad6cbc,Both Speaker As were equally persuasive,2026-02-16T10:12:34.555Z,60ff1c49e50b11c8d19c33dc,Speaker A from Debate 1,2026-02-18T12:35:04.636Z,569a54a5217ca2000cc93db0,Both Speaker As were equally persuasive,2026-02-20T19:46:57.078Z,NaN,NaN,NaN

In [20]:
comparison_ids = df["META_COMPARISONID"].unique().tolist()

annotator_cols = []
for col in df.columns:
    if col.startswith("Annotator") and col.endswith('_ID'):
        base = col.replace("_ID", "")
        annotator_cols.append((
            col,                          # ID column
            base + "_Timestamp",          # Timestamp column
            base + "_Response"            # Response column
        ))
annotator_cols

[('Annotator1_ID', 'Annotator1_Timestamp', 'Annotator1_Response'),
 ('Annotator2_ID', 'Annotator2_Timestamp', 'Annotator2_Response'),
 ('Annotator3_ID', 'Annotator3_Timestamp', 'Annotator3_Response'),
 ('Annotator4_ID', 'Annotator4_Timestamp', 'Annotator4_Response'),
 ('Annotator5_ID', 'Annotator5_Timestamp', 'Annotator5_Response'),
 ('Annotator6_ID', 'Annotator6_Timestamp', 'Annotator6_Response'),
 ('Annotator7_ID', 'Annotator7_Timestamp', 'Annotator7_Response'),
 ('Annotator8_ID', 'Annotator8_Timestamp', 'Annotator8_Response')]

In [21]:
def create_subgroup_df(main_df:pd.DataFrame, subgroup_df:pd.DataFrame, filename:str) -> pd.DataFrame:
    list_of_dict_data = []
    for idx, row in subgroup_df.iterrows():
        for col_id, col_ts, col_resp in annotator_cols:
            filtered = main_df[main_df[col_id] == row["Participant id"]]
            if not filtered.empty:
                for f_idx, f_row in filtered.iterrows():
                    for f_col_id, f_col_ts, f_col_resp in annotator_cols:
                        if main_df.at[f_idx, f_col_id] == row["Participant id"]:

                            data = {
                                    "DataPoint_ID": f_row["DataPoint_ID"],
                                    "META_COMPARISONID": f_row["META_COMPARISONID"],
                                    "META_COMPARISON": f_row["META_COMPARISON"],
                                    "Question": f_row["Question"],
                                    "Annotator_ID": f_row[f_col_id],
                                    "Annotator_Response": f_row[f_col_resp],
                                }
                            list_of_dict_data.append(data)

    combined_df = pd.DataFrame(list_of_dict_data)

    combined_df.to_csv(f"data/{filename}.csv")

In [22]:
new_df = create_subgroup_df(
    main_df=df,
    subgroup_df=left_pol_aff_df,
    filename="self-declared-left-leaning-annotators"
)

In [23]:
new_df = create_subgroup_df(
    main_df=df,
    subgroup_df=centre_pol_aff_df,
    filename="self-declared-centre-leaning-annotators"
)

In [24]:
new_df = create_subgroup_df(
    main_df=df,
    subgroup_df=right_pol_aff_df,
    filename="self-declared-right-leaning-annotators"
)

In [25]:
new_df = create_subgroup_df(
    main_df=df,
    subgroup_df=male_df,
    filename="self-declared-male-annotators"
)

In [26]:
new_df = create_subgroup_df(
    main_df=df,
    subgroup_df=female_df,
    filename="self-declared-female-annotators"
)

In [27]:
for label, age_df in age_group_dfs.items():
    if not age_df.empty:
        create_subgroup_df(
            main_df=df,
            subgroup_df=age_df,
            filename=f"self-declared-age-{label}-annotators"
        )